### ISSUE TITLE
Error within Apollo Client is not catched and creates an infinite loop

### ISSUE THREAD

**Issue by ChiefORZ** [trojanowski/react-apollo-hooks#23]
When a error within the `apollo-client` or the `react-apollo-hooks` library occurs it does not get returned as an error. React Suspend waits for the Promise, and tries to render it in an infinite loop.

https://codesandbox.io/s/zx2n727o33

even though a `Network Error` from `apollo-client` is written to the console every 50ms, the error does not get forwarded as an response to `useQuery`, nor does it get catched by `componentDidCatch`

**Comment by atoy40** [comment]
True, it loops over and over and let the "suspense" component in place instead of recalling the "query" component with "errors" populated".

**Comment by dan003400** [comment]
If the app is not able to connect to the server it will infinitely loop and retry.

**Comment by dan003400** [comment]
Same here, completely ignoring `apollo-link-retry`.

**Comment by atoy40** [comment]
I've just tested this 0.2 release, the infintite loop is gone, but I don't get the error with useQuery. I just have data and errors keys "undefined", while on-the-wire, I can see (partial) data and errors inside the server response. Any ideas ?

Anthony.

**Comment by atoy40** [comment]
@trojanowski It seems the reason of my previous message is due to typescript types. ApolloQueryResult has a key "errors" (an array of gql errors), but the object returned by useQuery contains only an "error" key.

**Comment by trojanowski** [comment]
@atoy40 Could you provide more details (maybe better in the #29 issue )? I I guess you use the `suspend: false` option (because there is a test case for errors with suspense: <https://github.com/trojanowski/react-apollo-hooks/blob/e1a9b6f77d2f9fb8c34ad89ee0ec5e3720e1b16d/src/__tests__/useQuery-test.js#L308>). Do you have 200 response from server?

> It seems the reason of my previous message is due to typescript types. ApolloQueryResult has a key "errors" (an array of gql errors), but the object returned by useQuery contains only an "error" key.

I going to rewrite this library to typescript in the future, so it should lower the chance of similar errors. Anyway I just forward the response from apollo client (<https://github.com/trojanowski/react-apollo-hooks/blob/e1a9b6f77d2f9fb8c34ad89ee0ec5e3720e1b16d/src/index.js#L70> and <https://github.com/trojanowski/react-apollo-hooks/blob/e1a9b6f77d2f9fb8c34ad89ee0ec5e3720e1b16d/src/index.js#L73>).

**Comment by atoy40** [comment]
@trojanowski yes I get a 200 response, with the "errors" key defined. But if i do :

```const result = useQuery<MyQuery>(QUERY);```

result contain only an "error" key, but not an "errors" key.
