### ISSUE TITLE
Nested query immediately freezes tests

### ISSUE THREAD

**Issue by VilhelmNielsen** [trojanowski/react-apollo-hooks#53]
First of all, great job on the package!

I'm currently writing tests for an application made with `react-apollo-hooks`, but I'm running into the issue where Jest simply freezes when I try to test queries that are deeper than one level, e.g.:

```graphql
query HelloQuery {
  hello {
    world
  }
}
```

I've tried to make a CodeSandbox of the issue, using @trojanowski example for tests, but please mind that CodeSandbox will try to run the tests immediately and in this case freeze the page entirely, so close the browser preview before the tests run:

https://codesandbox.io/s/40j6v77op4

**Comment by angeloashmore** [comment]
I'm not sure if this is an actual solution or just worked for me by chance, but I was running into the same issue where tests would hang at `waitForNextTick`. I finally fixed it by making sure the mocked query responses contained all data requested in the query with no warnings from Apollo.

**Comment by VilhelmNielsen** [comment]
@angeloashmore Thanks for your response. That sounds quite similar to the issue I'm running into, but I can't find any apparent errors in my mocked queries. Have you looked at the example I provided? Am I doing something wrong?

**Comment by angeloashmore** [comment]
@VilhelmNielsen Sorry for the late response. Just getting a chance to revisit the project that is using this lib.

Since Suspense is not SSR-ready yet with vanilla React, I decided to turn it off and fall back to the `loading` property. This seems to resolve the tests freezing. Sorry I don't have a better answer besides maybe turning off Suspense support. Depending on your setup, this could possibly be done just for tests.

**Comment by trojanowski** [comment]
@VilhelmNielsen could you please check if you still have this issue with the latest versions of react and react-apollo-hooks?

**Comment by VilhelmNielsen** [comment]
The latest version seems to solve the issue, thanks @trojanowski !
