### ISSUE TITLE
Suspense and server side rendering

### ISSUE THREAD

**Issue by strothj** [trojanowski/react-apollo-hooks#8]
Hello,

I was curious if you knew what the behavior would be like if this package was used with server side rendering.

My understanding is that Suspense is not currently supported when server side rendering. I think it shows loading state for Suspense components. I'm not sure how the interaction will play out when used in combination with the data collector from Apollo Server.

Do you happen to have any insight on this? Thank you.

**Comment by trojanowski** [comment]
Hi @strothj 

Yes, Suspense is not currently supported with SSR. The React team is working on a new server-side renderer with support for it, but it's going to be released (if I remember correctly) probably in the next year. However, we should be able to implement support for SSR in react-apollo-hooks even without it (similar how it was done it https://github.com/apollographql/react-apollo/pull/2533). The idea is that in the SSR mode we use an additional React context which provides, e.g. an array of promises to resolve and instead of throwing promises (as with suspense in the client mode), we add them to that array. Our SSR rendering function would invoke [renderToString](https://reactjs.org/docs/react-dom-server.html#rendertostring), and if there are any promises in the array it will wait for them to be resolved (repeating the process until everything will be resolved).

**Comment by atoy40** [comment]
Hi @trojanowski,
Is it really a good idea to throw a promise and enforce the use of Suspense ? the result contains all you need to check on the component (for example the 'loading' key).
I 've commented it, and it's imho more easy to use. But may be I missed something :)

Thks
Anthony.

**Comment by atoy40** [comment]
@trojanowski Thanks for this reply, after some tests since my message ... I agree :) it's easy to use and will become something standard.

**Comment by langpavel** [comment]
I created #27 where you can easily configure if you want suspense by default
I think about adding configuration to context but I didn't like it

**Comment by geirman** [comment]
I was playing with this in a NextJS app that was already setup for SSR, so that `<Query>` was run before the page was delivered to the client. I would never see "Loading..." on initial page load. Swapping out the query render prop with the hooks caused "Loading..." to show briefly on each full refresh. Is there something I need to be doing differently to get the SSR to work?

**Comment by langpavel** [comment]
As stated above, suspense is not ready for SSR. I'm excited about too, but I'm waiting...
